trigger: 
  - main
stages:
  - stage: Build
    displayName: Build java app...
    jobs: 
      - job: Buid
        displayName: Building the mvn application...
        pool: default
        steps: 
           - script: mvn package -DskipTests=true
             displayName: packaging the application
           - task: CopyFiles@2
             inputs:
               Contents: '**/*.jar'
               TargetFolder: '$(build.artifactstagingdirectory)'
             displayName: Copying to the artifacts folder
           - task: CopyFiles@2
             inputs:
               Contents: 'kube-manifests'
               TargetFolder: '$(build.artifactstagingdirectory)'
           
           - task: PublishBuildArtifacts@1
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)'
               ArtifactName: 'petclininc app'
               publishLocation: 'Container'
             displayName: Publishing the artifacts
           - task: Docker@2
             inputs:
               containerRegistry: 'acr0877'
               repository: 'petclininc'
               command: 'buildAndPush'
               Dockerfile: 'Dockerfile'