name: Build Java code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      log_level:
        description: Log level
        required: false
        default: INFO

jobs:
  build-test:
    name: Maven build (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
            java-version: ${{ matrix.java }}
          cache: maven
      - name: Show log level
        run: echo "LOG_LEVEL=${{ github.event.inputs.log_level || 'INFO' }}"
      - name: Build & test
        run: ./mvnw -B clean verify
      - name: Upload JAR
        if: matrix.java == '17'
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
      - name: Upload coverage report
        if: matrix.java == '17'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

  docker-image:
    name: Docker build
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Package
        run: ./mvnw -DskipTests package
      - name: Build image
        run: docker build -t ${{ github.repository }}:latest .
      # - name: Login & push
      #   env:
      #     REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      #     REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
      #   run: |
      #     echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
      #     docker tag ${{ github.repository }}:latest your-registry/your-image:latest
      #     docker push your-registry/your-image:latest
